### ISSUE TITLE
[BUG] Reference data links not going to specific reference instance

### ISSUE THREAD

**Issue by roleyfoley** [hamlet-io/docs#91] opened 2021-02-10 00:58 UTC
## Description
When browsing the docs reference site ( https://docs.hamlet.io/reference ) if I click on a Reference Data instance from the menu the page shows all references and doesn't take me to the reference information I selected and shows all reference data 

E.g. https://docs.hamlet.io/reference?type=reference&instance=Bootstrap shows the AlertProfiles reference along with the rest of the references

**Comment by RossMurr4y** [comment] 2021-02-10 05:15
This was known to me but not adequately expressed in "followup actions" on recent PR's.

Despite how it appears, the docs site is correctly portraying the JSONSchema its been told to load. The origin bug was in the Hamlet engine and was resolved [here](https://github.com/hamlet-io/engine/pull/1524) however due to the Github Action that publishes the schemas to the docs site breaking (likely due to the way the engine and CLI have changed to generating schema instances) outlined here https://github.com/hamlet-io/docs/issues/93

This can be seen in the currently published JSONSchema for [Bootstrap](https://github.com/hamlet-io/docs/blob/master/static/schema/latest/blueprint/schema-reference-bootstrap-schema.json).

I'll keep this open to ensure its resolved alongside the Github Action

**Comment by RossMurr4y** [comment] 2021-02-10 07:24
Github Action has been updated / published, new schemas have been published and are now working as intended. See https://docs.hamlet.io/reference?type=reference&instance=Bootstrap

Closing.

**Closed by RossMurr4y** 2021-02-10 07:24 UTC
Labels: bug
